name: 'clara_case'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'clara_case'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  clara_case:
    # Config indicated by + and applies to all files under models/marts/
    marts:
      +materialized: table
    stagging:
      # The config bellow is used to not created the tables in production, however
      # create in development. This is used because the stagging will be only used
      # in few models and will be the replica of the raw with mininal changes. 
      +materialized: "{{ 'ephemeral' if target.name=='prod' else 'table' }}"