edenred_serv_dbt:
  target: "{{ env_var('DEFAULT_TARGET') }}"
  outputs:

    dev:
      type: databricks
      schema: "{{ env_var('DEV_SCHEMA') }}"
      host: "{{ env_var('DEV_HOST') }}"
      http_path: "{{ env_var('DEV_HTTP_PATH') }}"
      token: "{{ env_var('DEV_TOKEN') }}"
      threads: 16

    ci:
      type: databricks
      schema: "{{ env_var('CI_SCHEMA') }}"
      host: "{{ env_var('CI_HOST') }}"
      http_path: "{{ env_var('CI_HTTP_PATH') }}"
      token: "{{ env_var('CI_TOKEN') }}"
      threads: 16

    prod:
      type: databricks
      schema: "{{ env_var('PROD_SCHEMA') }}"
      host: "{{ env_var('PROD_HOST') }}"
      http_path: "{{ env_var('PROD_HTTP_PATH') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 16
