clara_case:

  target: "{{ env_var('DEFAULT_TARGET') }}"
  outputs:
    dev:
        type: bigquery
        method: service-account
        project: clara-case
        dataset: "{{ env_var('DEV_DATASET') }}"
        threads: 4 # Must be a value of 1 or greater
        keyfile: "{{ env_var('DEV_KEYFILE') }}"
        location: us-central1

    prod:
        type: bigquery
        method: service-account
        project: clara-case
        dataset: "{{ env_var('PROD_DATASET') }}"
        threads: 4 # Must be a value of 1 or greater
        keyfile: "{{ env_var('PROD_KEYFILE') }}"
        location: us-central1