clara_case:

  target: "{{ env_var('DEFAULT_TARGET') }}"
  outputs:
    dev:
        type: bigquery
        method: service-account
        project: clara-case
        dataset: bronze
        threads: 4 # Must be a value of 1 or greater
        keyfile: "{{ env_var('DEV_KEYFILE') }}"
